# 开发环境XXL-JOB配置
xxl:
  job:
    enabled: true
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken: ""
    executor:
      appname: lst-project-executor
      address: ""
      ip: ""
      port: 9999
      logpath: ./data/applogs/xxl-job/jobhandler
      logretentiondays: 30