# 生产环境XXL-JOB配置
xxl:
  job:
    enabled: true
    admin:
      addresses: http://xxl-job-admin.prod:8080/xxl-job-admin
    accessToken: ""
    executor:
      appname: lst-project-executor
      address: ""
      ip: ""
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30